online/urls.py
from django.urls import path
from . import views

#paths for account app. 
urlpatterns = [
    path('',views.OnlineView, name='onlineView_url'),
    path('editEBook/<str:pk>',views.EditEBookView, name='editEBookView_url'),
    path('softDeleteEBook/',views.SoftDeleteEBookView, name='softDeleteEBookView_url'),
    path('allEBooks/', views.AllEBooksView, name='allEBooks_url'),
    path('createeBook/',views.CreateeBookView, name='createeBook_url'),
    path('readeBook/<str:pk>',views.ReadeBookView, name='readeBook_url'),  
    path('vieweBook/<str:pk>',views.VieweBookView, name='vieweBook_url'),
    path('readeBookView/',views.ReadeBookStatusView, name='readeBookView_url'),
]

timp_lab/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
#redirecting to home page..
from django.views.generic import RedirectView

import uaa

urlpatterns = [
    
    path('login_url/',include('uaa.urls')),
    path('',RedirectView.as_view(url='/login_url/')),
    
    path('tipmAdmin/', admin.site.urls),
    path('',include("uaa.urls")),
    path('book/',include("book.urls")),
    path('online/', include("online.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

uaa/urls.py
from django.urls import path
from . import views

#paths for account app.
urlpatterns = [
    path('',views.LoginView, name='login_url'),
    path('logout',views.LogoutView, name='logout_url'),
    path('registrationNoView',views.RegistrationNoView, name='registrationNoView_url'),
    path('addRegNo',views.AddRegNoView, name='addRegNo_url'),
    path('register/',views.RegisterView, name="register_url"),
    path('addUser/',views.AddUserView, name='addUser_url'), 
    path('updateUserView/<str:pk>',views.UpdateUserView, name='updateUserView_url'),
    path('dashboard/',views.DashboardView, name='dashboard_url'),
    
    path('profile/',views.ProfileView, name='profile_url'),
    path('update_profile/',views.UpdateProfileView, name='update_profile_url'),
    path('allUsers/',views.AllUsersView, name='allUsers_url'), 
    path('updatePasswordView/',views.UpdatePasswordView, name='updatePasswordView_url'),
    path('forgotPasswordView/',views.ForgotPasswordView, name='forgotPasswordView_url'),
    path('resetPasswordView/',views.ResetPasswordView, name='resetPasswordView_url'),
    path('userStatusView/',views.UserStatusView, name='userStatusView_url'),  
    path('tipButtonView/',views.TipButtonView, name='tipButtonView_url'),
    path('tipView/',views.TipView, name='tipView_url'), 
    path('manageTip/', views.ManageTipsView, name="manageTip_url"),
    path('deleteTips/<str:pk>', views.DelateTipsView, name="deleteTips_url"),
]

online/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from book.models import Category
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext as _
import uuid
from uaa.models import User


# Create your models here.
class EBook(models.Model):
    id = models.UUIDField(editable=False, default=uuid.uuid4, unique=True,primary_key=True)
    createdBy = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name="user_eBook_creator",blank=True,null=True)
    categoryId = models.ForeignKey(Category,on_delete=models.DO_NOTHING,related_name="category_e_Book",blank=True,null=True)
    title = models.CharField(max_length=255,blank=True,null=True)
    author = models.CharField(max_length=50,blank=True,null=True)
    publisher = models.CharField(max_length=50,blank=True,null=True)
    yearOfPublication = models.CharField(max_length=50,blank=True,null=True)
    coverPageeBook = models.FileField(upload_to='coverPageImages', validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])]) 
    eBookFile = models.FileField(null=True, blank=True,upload_to='onlineeBook', validators=[FileExtensionValidator(['pdf'])])
    status = models.BooleanField(default=True) 
    
    createdAt = models.DateField(auto_now_add=True)
    updatedAt = models.DateField(auto_now=True)
    
    class Meta: 
        ordering = ['-createdAt']
    
    def __str__(self):
        return self.title
    
class ReadeBook(models.Model):
    id = models.UUIDField(editable=False, default=uuid.uuid4, unique=True,primary_key=True)
    bookId = models.ForeignKey(EBook,on_delete=models.CASCADE,related_name="readEbook",blank=True,null=True)
    readNo = models.IntegerField(default=1,blank=True)
    status = models.BooleanField(default=True) 
    
    updatedAt = models.DateField(auto_now=True)
    
    class Meta: 
        ordering = ['-updatedAt']
    
    def __str__(self):
        return str(self.readNo)

uaa/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.core.validators import FileExtensionValidator
# from django.utils.translation import gettext as _
from django.conf import settings
from django.core.validators import RegexValidator
import uuid


# from uuidfield import UUIDField
class REgisterdMember(models.Model):
      id = models.UUIDField(editable=False, default=uuid.uuid4, unique=True,primary_key=True)
      regNo = models.CharField(max_length=25,blank=False,null=True)
      
      createdAt = models.DateField(auto_now_add=True)
      updatedAt = models.DateField(auto_now=True)
      
      class Meta: 
            ordering = ['-createdAt']
      
      def __str__(self):
          return str(self.regNo)
      
      
class User(AbstractUser):
      email = models.EmailField(_('email address'), unique = True)
      nida_no = models.CharField(max_length=25, null=True, blank=True)
      phone_number = models.CharField(max_length=15, blank=True,null=True)
      dob = models.DateField(null=True,blank=True)
      gender = models.CharField(max_length=6,blank=True,null=True)
      profileImage = models.FileField(upload_to='profileImages/', validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])], default='profileImages/profile_default.png',null=True,blank=True)
      
      USERNAME_FIELD = 'email'
      REQUIRED_FIELDS = ['username','first_name','last_name']

      def __str__(self):
        return "{}".format(self.email)
      
      
class DailyTip(models.Model):
      id = models.UUIDField(editable=False, default=uuid.uuid4, unique=True,primary_key=True)
      content = models.CharField(max_length=255,blank=True,null=True)
      status = models.BooleanField(default=True)
      
      createdAt = models.DateField(auto_now_add=True)
      updatedAt = models.DateField(auto_now=True)
      
      class Meta: 
            ordering = ['-createdAt']
          
      def __str__(self):
          return str(self.content)
      
  

online/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.db.models import Q
from uaa.decorators import admin_only, allowed_users, manager_only, unauthenticated_user
from online.models import EBook,ReadeBook
from book.models import Category
from django.http import FileResponse,Http404,HttpResponse
import os

# Create your views here.
@unauthenticated_user
@allowed_users(allowed_roles=['manager','admin'])
def OnlineView(request):
    EBookObjectList = EBook.objects.filter(status=True)
    
    context = {"EBookObject":EBookObjectList}
    return render(request,"online/onlinePage.html",context)   

@unauthenticated_user
@admin_only
def EditEBookView(request, pk):
    
    bookCategoryObject = Category.objects.all()
    editEBookObject = EBook.objects.filter(id=pk).first()
    
    if request.method == "POST":
        categoryId = request.POST.get('categoryId')
        title = request.POST.get('title')
        author = request.POST.get('author')
        publisher = request.POST.get('publisher')
        yearOfPublication = request.POST.get('yearOfPublication')
        
        try:
            editEBookObject.categoryId_id = categoryId
            editEBookObject.createdBy_id=request.user.id 
            editEBookObject.title = title
            editEBookObject.author = author
            editEBookObject.publisher = publisher
            editEBookObject.yearOfPublication = yearOfPublication
            editEBookObject.save()
            
            messages.info(request,'sucessfully, Updated')
            return redirect('onlineView_url')
    
        except Exception as e:
            print(e)
    
    context = {"categoty_id":bookCategoryObject,"editEBookObjectData":editEBookObject}
    return render(request,"online/onlineEditEBook.html",context)


@unauthenticated_user
@admin_only
def SoftDeleteEBookView(request): 
    try:
        SoftDeleteEBookObject = get_object_or_404(EBook,pk=request.GET.get('eBook_id'))
        SoftDeleteEBookObject.status = not SoftDeleteEBookObject.status
        SoftDeleteEBookObject.save()
        return redirect('onlineView_url')

    except Exception as e:
        print(e)
        

@unauthenticated_user
@allowed_users(allowed_roles=['stuff','student'])
def AllEBooksView(request):
    
    categotyIdObject = Category.objects.all()
    
    try:
        if 'q' in request.GET:
            q = request.GET['q']
            #data = Book.objects.filter(title__icontains=q)
            multiple_data = Q(Q(title__icontains=q) |             
                            Q(author__icontains=q) | 
                            Q(publisher__icontains=q) | 
                            Q(yearOfPublication__icontains=q) | 
                            Q(categoryId__id__icontains=q))
            
            ebookObject = EBook.objects.filter(multiple_data,status=True)
        
        else:
            ebookObject = EBook.objects.filter(status=True)
        
    except FileNotFoundError:
        raise Http404
    
    context = {'ebook':ebookObject,'categoty_id':categotyIdObject}
    return render(request,'online/onlineAlleBooks.html', context)


@unauthenticated_user
@admin_only
def CreateeBookView(request):
    bookCategoryObject = Category.objects.all()
    
    if request.method == "POST" and 'coverPageeBook' in request.FILES and 'eBook' in request.FILES:
        categoryId = request.POST.get('categoryId')
        title = request.POST.get('title')
        author = request.POST.get('author')
        publisher = request.POST.get('publisher')
        yearOfPublication = request.POST.get('yearOfPublication')
        
        coverPagee = request.FILES
        coverPageeBook = coverPagee['coverPageeBook']
        eBookFile = request.FILES
        eBook = eBookFile['eBook']
        
        try:
            eBookCreateObject = EBook.objects.create(
                createdBy_id=request.user.id,
                categoryId_id=categoryId,
                title=title,
                author=author,
                publisher=publisher,
                yearOfPublication=yearOfPublication,
                coverPageeBook=coverPageeBook,
                eBookFile=eBook
            )
            
            eBookCreateObject.save()
            messages.info(request,'sucessfully, Created')
            return redirect('onlineView_url')
        
        except FileNotFoundError:
            raise Http404
    
    context = {"categoty_id":bookCategoryObject}
    return render(request,"online/createebook.html",context)


@unauthenticated_user
@allowed_users(allowed_roles=['manager','admin'])
def ReadeBookView(request, pk):
    try:
        eBookObject = EBook.objects.get(id=pk)
        
        with open(str(eBookObject.eBookFile.path), 'rb') as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = 'inline; filename="eBook.pdf"'
            return response
        pdf.closed
    
    except FileNotFoundError:
        raise Http404


@unauthenticated_user
@allowed_users(allowed_roles=['stuff','student'])
def VieweBookView(request, pk):
    try:
        VieweBookObject = EBook.objects.get(id=pk)
        readeBookObject = ReadeBook.objects.filter(bookId=pk).first()
        
        if readeBookObject:
            readeBookObject.readNo += 1
            readeBookObject.save()
        else:
            saveReadeBookData = ReadeBook.objects.create(
                bookId_id=pk,
            )
            saveReadeBookData.save()
        
        with open(str(VieweBookObject.eBookFile.path), 'rb') as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = 'inline; filename="eBook.pdf"'
            return response
        pdf.closed
    
    except FileNotFoundError:
        raise Http404


@unauthenticated_user
@allowed_users(allowed_roles=['manager','admin'])
def ReadeBookStatusView(request):
    readeBookObject = ReadeBook.objects.filter(status=True).order_by("-readNo")
    
    context = {"readeBookData":readeBookObject}
    return render(request,'online/readeBookStatus.html', context)

templates/online/createebook.html
{% extends 'base/mainbase.html' %}
{% block content %}
{% load static %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>e-Book</h1>

            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-info">
                {{ message }}
              </div>
             {% endfor %}
            {% endif %}

          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard_url' %}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{% url 'onlineView_url' %}">Back</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">

          </div>
          <!-- /.col -->
          <div class="col-md-8">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Create e-Book Now</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="tab-pane" id="settings">

                    <form method="POST" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Book Category: </label>
                        <select class="col-sm-10" id="selectGender" name="categoryId">
                          {% for book_category in categoty_id %}
                          <option value="{{ book_category.id }}">{{ book_category.categoryName }}</option>
                          {% endfor %}
                        </select>
                      </div> 

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Title: </label>
                        <div class="col-sm-10">
                          <input type="text" name="title" class="form-control" id="inputName" placeholder="The story danger" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Author: </label>
                        <div class="col-sm-10">
                          <input type="text" name="author" class="form-control" id="inputName" placeholder="isbmm kiombo" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Publisher: </label>
                        <div class="col-sm-10">
                          <input type="text" name="publisher" class="form-control" id="inputName" placeholder="tipm institute">
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Year Of Publication: </label>
                        <div class="col-sm-10">
                          <input type="text" name="yearOfPublication" class="form-control" id="inputName" placeholder="2003">
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Cover Page e-Book</label>
                        <div class="col-sm-10">
                          <input type="file" accept="application/jpeg" name="coverPageeBook" class="form-control" id="inputName" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Upload e-Book</label>
                        <div class="col-sm-10">
                          <input type="file"  accept="application/pdf" name="eBook" class="form-control" id="inputName" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">save</button>
                        </div>
                      </div>

                    </form>

                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% endblock content %}

templates/online/onlineAlleBooks.html
{% extends 'base/mainbase.html' %}
{% block content %}
{% load static %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-3">
            <h4 class="m-0"><a href="{% url 'Book_url' %}"><u>All Books</u></a></h4>
            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-info">
                {{ message }}
              </div>
            {% endfor %}
            {% endif %}
          </div><!-- /.col -->

          <div class="col-sm-5">
            <form class="form-inline my-2 my-lg-0">
              <div class="form-control mr-sm-2">
              <select class="col-sm-10" style="width: 100%; border:none;" id="selectBookCategoryId" name="q">
                {% for cat in categoty_id %}
                <option style="width: 100%; border:none;" value="{{ cat.id }}">{{ cat.categoryName }}</option>
                {% endfor %}
              </select>
              </div>
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>

          <div class="col-sm-4">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" name="q" placeholder="search book" aria-label="search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div><!-- /.col -->

        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
 

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">

          <div class="clearfix hidden-md-up"></div>
            
            {% for bk in ebook %}
            <div class="col-12 col-sm-6 col-md-3 modify">
                <div class="bg-light clearfix">
                  <p><strong>title : </strong>{{bk.title}}</p>
                </div>
                  <div class="info-box mb-3">
                      {% if bk.coverPageeBook %}
                      <img src="{{bk.coverPageeBook.url}}" class="img-fluid" title="read/download {{bk.title}} pdf">
                      {% endif %}
                  </div>

                  <div class="bg-light clearfix">
                    <div class="float-left">
                      <a href="{% url 'vieweBook_url' bk.id %}" title="read online"><i class="fa fa-book-open"></i></a>
                    </div>
                    <div class="float-right">  
                      {% if bk.eBookFile %}
                      <a href="{{ bk.eBookFile.url }}" download title="download"><i class="fas fa-download"></i></a>
                      {% else %}
                      <span class="text-muted"><i class="fa fa-times"></span>
                      {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}

            
        </div>
        <!-- /.row -->
      </div><!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% endblock content %}

templates/online/onlineEditEBook.html
{% extends 'base/mainbase.html' %}
{% block content %}
{% load static %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h3>Edit e-Book</h3>

            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-info">
                {{ message }}
              </div>
             {% endfor %}
            {% endif %}

          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard_url' %}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{% url 'onlineView_url' %}">Back</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">

          </div>
          <!-- /.col -->
          <div class="col-md-8">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Edit e-Book Now</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="tab-pane" id="settings">

                    <form method="POST" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Book Category: </label>
                        <select class="col-sm-10" id="selectGender" name="categoryId">
                          {% for book_category in categoty_id %}
                          <option value="{{ book_category.id }}">{{ book_category.categoryName }}</option>
                          {% endfor %} editEBookObjectData
                        </select>
                      </div> 

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Title: </label>
                        <div class="col-sm-10">
                          <input type="text" name="title" class="form-control" id="inputName" value="{{ editEBookObjectData.title }}" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Author: </label>
                        <div class="col-sm-10">
                          <input type="text" name="author" class="form-control" id="inputName" value="{{ editEBookObjectData.author }}" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Publisher: </label>
                        <div class="col-sm-10">
                          <input type="text" name="publisher" class="form-control" id="inputName" value="{{ editEBookObjectData.publisher }}" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Year Of Publication: </label>
                        <div class="col-sm-10">
                          <input type="text" name="yearOfPublication" class="form-control" id="inputName" value="{{ editEBookObjectData.yearOfPublication }}" required>
                        </div>
                      </div>

                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">save</button>
                        </div>
                      </div>

                    </form>

                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% endblock content %}

templates/online/onlinePage.html
{% extends 'base/mainbase.html' %}
{% block content %}
{% load static %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Manage e-Books</h1>

            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-info">
                {{ message }}
              </div>
             {% endfor %}
            {% endif %}

          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard_url' %}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{% url 'profile_url' %}">My Profile</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

          <section class="#">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-10">
                  <p>Manage and update library e-books</p>
                </div>

                {% if perms.uaa.delete_user %}
                <div class="col-sm-2">
                  <a class="btn btn-primary pull-right" href="{% url 'createeBook_url' %}">Add e-Book</a>
                </div>
                {% endif %}
                
              </div>
            </div><!-- /.container-fluid -->
          </section>

          <!-- /.card-header -->
          <div class="card-body">
            <table id="example1" class="table table-sm mx-auto table-bordered table-striped">
              <thead>
                <tr>
                  <th>S/n</th>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Author</th>
                  <th>Publicshed By</th>
                  <th>Year Publicshed</th>

                  {% if perms.uaa.delete_user %}
                  <th>Actions</th>
                  {% endif %}

                </tr>
              </thead>
              <tbody>
                {% for EBookObjectData in EBookObject %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ EBookObjectData.title }}</td>
                  <td>{{ EBookObjectData.categoryId.categoryName }}</td>
                  <td>{{ EBookObjectData.author }}</td>
                  <td>{{ EBookObjectData.publisher }}</td>
                  <td>{{ EBookObjectData.yearOfPublication }}</td>

                  {% if perms.uaa.delete_user %}
                  <td>
                    <a class="fa fa-eye btn-sm btn-primary" title="view" href="{% url 'readeBook_url' EBookObjectData.id %}"></a>
                    <a class="fa fa-edit btn-sm btn-primary" title="view/edit" href="{% url 'editEBookView_url' EBookObjectData.id %}"></a>
                    <a class="fa fa-trash btn-sm btn-danger" title="delete" href="{% url 'softDeleteEBookView_url' %}?eBook_id={{EBookObjectData.id}}"></a>
                  </td>
                  {% endif %}
                  
                </tr>
                {% endfor %}
              </tbody>
              <tfoot>
                <tr>
                  <th>S/n</th>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Author</th>
                  <th>Publicshed By</th>
                  <th>Year Publicshed</th>

                  {% if perms.uaa.delete_user %}
                  <th>Actions</th>
                  {% endif %}

                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
       
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% endblock content %}